name: ex2

on :
  push:
    branches:
    - master
    
jobs:
    
    Myjob1:
      runs-on: windows 11
      steps:
      - name: print msg
        run: ecko "hello "
      - name: hash code
        run: ecko "
    
